spring:
  application:
    name: api-gateway

server:
  port: 8080

zuul:
  routes:
    course:
      path: /course/**
      url: http://${ROUTE_COURSE_HOST:localhost}:${ROUTE_COURSE_PORT:8081}/course/
    user:
      path: /user/**
      url: http://${ROUTE_USER_HOST:localhost}:${ROUTE_USER_PORT:8082}/user/
