spring:
  application:
    name: course-dubbo-seevice
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:db_course}?useSSL=false
    username: ${MYSQL_USER:micro}
    password: ${MYSQL_PASSWORD:aA123456}
    driver-class-name: com.mysql.jdbc.Driver

dubbo:
  server: true
  application:
    id: course-service-provider
    name: course-service-provider
  registry:
    address: zookeeper://${ZK_HOST:127.0.0.1}:${ZK_PORT:2181}
  protocol:
    name: dubbo
    port: 20880
  scan:
    basePackages: com.yourtion.micro.course

thrift:
  user:
    ip: ${THRIFT_USER_HOST:127.0.0.1}
    port: ${THRIFT_USER_PORT:7911}
