server:
  name: user-service
  port: 7911

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:db_user}?useSSL=false
    username: ${MYSQL_USER:micro}
    password: ${MYSQL_PASSWORD:aA123456}
    driver-class-name: com.mysql.jdbc.Driver